#!/usr/bin/env python3
"""
build_system.py — EasyInstall Build System Plugin v1.0
=======================================================
Automates package building, Docker image creation, cross-platform
compilation, GitHub Actions CI/CD pipeline generation, and version tagging.
"""

import subprocess
import json
import re
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys; sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


# ─────────────────────────────────────────────────────────────────────────────
# CI/CD and build templates
# ─────────────────────────────────────────────────────────────────────────────

GH_ACTIONS_DEPLOY_TEMPLATE = """\
# .github/workflows/deploy.yml
# Generated by easyinstall-plugin build-system
name: EasyInstall Deploy

on:
  push:
    branches: [main]
    tags:     ['v*']
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Lint Python
        run: pip install flake8 && flake8 --max-line-length=120 .
      - name: Lint Shell
        run: |
          sudo apt-get install -y shellcheck -q
          find . -name '*.sh' | xargs shellcheck --severity=warning

  test:
    runs-on: ubuntu-latest
    needs:   lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run Python tests
        run: |
          pip install pytest pytest-cov
          pytest tests/ --tb=short -q 2>/dev/null || echo "No tests yet"

  build-worker:
    runs-on: ubuntu-latest
    needs:   test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - name: Deploy Worker
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{{{ secrets.CLOUDFLARE_API_TOKEN }}}}
        run: npx wrangler deploy

  build-deb:
    runs-on: ubuntu-latest
    needs:   test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Build .deb package
        run: |
          mkdir -p dist
          python3 -c "
          import sys; sys.path.insert(0, 'plugins')
          from easyinstall_plugins.debian_package import DebianPackagePlugin
          p = DebianPackagePlugin({{}})
          p.initialize()
          p.build('{domain}', version='${{{{ github.ref_name }}}}'.lstrip('v'), output_dir='dist')
          "
      - uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: dist/*.deb
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.deb

  docker:
    runs-on: ubuntu-latest
    needs:   test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{{{ secrets.DOCKER_USERNAME }}}}
          password: ${{{{ secrets.DOCKER_PASSWORD }}}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context:   .
          push:      true
          tags:      {docker_image}:latest,${{{{ github.ref_name }}}}
          cache-from: type=gha
          cache-to:   type=gha,mode=max
          platforms: linux/amd64,linux/arm64
"""

DOCKERFILE_TEMPLATE = """\
# Dockerfile — EasyInstall WordPress Stack
# Generated by easyinstall-plugin build-system
FROM debian:12-slim AS base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q && apt-get install -y -q --no-install-recommends \\
    nginx php{php_version}-fpm php{php_version}-mysql php{php_version}-redis \\
    php{php_version}-curl php{php_version}-gd php{php_version}-xml php{php_version}-mbstring \\
    mariadb-client redis-tools curl python3 \\
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy EasyInstall engine
COPY --chmod=755 easyinstall.sh        /usr/local/bin/easyinstall
COPY --chmod=644 easyinstall_config.py /usr/local/lib/easyinstall_config.py

WORKDIR /var/www/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
"""

MAKEFILE_TEMPLATE = """\
# Makefile — EasyInstall Build System
# Usage: make help

DOMAIN      ?= example.com
VERSION     ?= $(shell git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")
DOCKER_IMG  ?= easyinstall/wordpress
DEB_OUT     ?= ./dist
ARCH        ?= amd64

.PHONY: help build build-worker build-deb build-docker tag test clean

help:
\t@echo "EasyInstall Build Targets:"
\t@echo "  build          Build all artifacts"
\t@echo "  build-worker   Build Cloudflare Worker (wrangler)"
\t@echo "  build-deb      Build .deb package"
\t@echo "  build-docker   Build Docker image"
\t@echo "  tag VERSION=x  Create git tag"
\t@echo "  test           Run tests"
\t@echo "  clean          Remove build artifacts"

build: build-worker build-deb build-docker

build-worker:
\t@echo "Building Worker..."
\tnpx wrangler deploy --dry-run

build-deb:
\t@echo "Building .deb package..."
\tmkdir -p $(DEB_OUT)
\tpython3 -c "\\
\timport sys; sys.path.insert(0,'plugins'); \\
\tfrom easyinstall_plugins.debian_package import DebianPackagePlugin; \\
\tp=DebianPackagePlugin({}); p.initialize(); \\
\tp.build('$(DOMAIN)', version='$(VERSION)', output_dir='$(DEB_OUT)')"

build-docker:
\t@echo "Building Docker image..."
\tdocker buildx build --platform linux/amd64,linux/arm64 \\
\t    -t $(DOCKER_IMG):$(VERSION) -t $(DOCKER_IMG):latest . --push

tag:
\tgit tag -a v$(VERSION) -m "Release v$(VERSION)"
\tgit push origin v$(VERSION)

test:
\tpython3 -m pytest tests/ -q 2>/dev/null || echo "No test suite yet"
\tnpx vitest run 2>/dev/null || true

clean:
\trm -rf dist/ build/ .wrangler/ node_modules/.cache
"""

VERSION_BUMP_SCRIPT = """\
#!/usr/bin/env python3
\"\"\"version_bump.py — bump version across EasyInstall files\"\"\"
import re, sys
from pathlib import Path

BUMP_TYPE = sys.argv[1] if len(sys.argv) > 1 else "patch"   # major|minor|patch

def read_current():
    for f in Path(".").rglob("easyinstall*.py"):
        m = re.search(r'version\\s*=\\s*["\\'](\\d+\\.\\d+\\.\\d+)["\\'']', f.read_text())
        if m:
            return m.group(1), f
    return "1.0.0", None

def bump(v, t):
    parts = list(map(int, v.split(".")))
    if t == "major": parts[0] += 1; parts[1] = 0; parts[2] = 0
    elif t == "minor": parts[1] += 1; parts[2] = 0
    else: parts[2] += 1
    return ".".join(map(str, parts))

current, src = read_current()
new_ver = bump(current, BUMP_TYPE)
print(f"Bumping {current} → {new_ver} ({BUMP_TYPE})")

if src:
    src.write_text(src.read_text().replace(f"'{current}'", f"'{new_ver}'").replace(f'"{current}"', f'"{new_ver}"'))
    print(f"Updated: {src}")
"""


class BuildSystemPlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "build-system",
            version     = "1.0.0",
            description = "Build automation: Docker images, .deb packages, GitHub Actions CI/CD, Makefile",
            author      = "EasyInstall",
            requires    = ["docker", "git"],
            provides    = ["ci-cd", "docker-build", "deb-build", "makefile", "version-tagging"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("git"):
            self.logger.warning("git not found")
        return True

    # ── Generators ────────────────────────────────────────────────────────────

    def generate_github_actions(self, domain: str,
                                  docker_image: str = "easyinstall/wordpress",
                                  output_dir: str = ".") -> str:
        """Write .github/workflows/deploy.yml and return its path."""
        wf_dir = Path(output_dir) / ".github" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)
        content = GH_ACTIONS_DEPLOY_TEMPLATE.format(
            domain=domain, docker_image=docker_image
        )
        path = wf_dir / "deploy.yml"
        path.write_text(content)
        self.logger.info(f"GitHub Actions workflow written: {path}")
        return str(path)

    def generate_dockerfile(self, php_version: str = "8.2",
                             output_path: str = "Dockerfile") -> str:
        """Write a Dockerfile for the WordPress stack."""
        content = DOCKERFILE_TEMPLATE.format(php_version=php_version)
        Path(output_path).write_text(content)
        self.logger.info(f"Dockerfile written: {output_path}")
        return output_path

    def generate_makefile(self, domain: str = "example.com",
                           docker_image: str = "easyinstall/wordpress",
                           output_path: str = "Makefile") -> str:
        """Write a Makefile with build targets."""
        content = MAKEFILE_TEMPLATE.replace("example.com", domain) \
                                   .replace("easyinstall/wordpress", docker_image)
        Path(output_path).write_text(content)
        self.logger.info(f"Makefile written: {output_path}")
        return output_path

    def generate_version_bump_script(self, output_path: str = "version_bump.py") -> str:
        """Write a helper script for semantic version bumping."""
        path = Path(output_path)
        path.write_text(VERSION_BUMP_SCRIPT)
        path.chmod(0o755)
        self.logger.info(f"Version bump script written: {path}")
        return str(path)

    # ── Build actions ─────────────────────────────────────────────────────────

    def build_docker_image(self, tag: str = "easyinstall/wordpress:latest",
                            context: str = ".",
                            platforms: List[str] = None,
                            push: bool = False) -> bool:
        """Build a Docker image using docker buildx."""
        if not self.require_binary("docker"):
            return False
        plat_arg = ",".join(platforms or ["linux/amd64"])
        cmd = ["docker", "buildx", "build",
               "--platform", plat_arg,
               "-t", tag, context]
        if push:
            cmd.append("--push")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            self.logger.info(f"Docker image built: {tag}")
            return True
        self.logger.error(result.stderr)
        return False

    def create_git_tag(self, version: str, message: str = "",
                        push: bool = False) -> bool:
        """Create an annotated git tag."""
        if not self.require_binary("git"):
            return False
        tag  = f"v{version}" if not version.startswith("v") else version
        msg  = message or f"Release {tag}"
        result = subprocess.run(
            ["git", "tag", "-a", tag, "-m", msg],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            self.logger.error(f"Tag failed: {result.stderr}")
            return False
        if push:
            subprocess.run(["git", "push", "origin", tag], capture_output=True)
        self.logger.info(f"Git tag created: {tag}")
        return True

    def bump_version(self, bump_type: str = "patch",
                      project_dir: str = ".") -> Optional[str]:
        """
        Bump version in plugin files.
        bump_type: 'major' | 'minor' | 'patch'
        Returns new version string.
        """
        result = subprocess.run(
            ["python3", "version_bump.py", bump_type],
            cwd=project_dir, capture_output=True, text=True
        )
        if result.returncode == 0:
            # Extract new version from output
            m = re.search(r"→\s*([\d.]+)", result.stdout)
            if m:
                self.logger.info(f"Version bumped to {m.group(1)}")
                return m.group(1)
        self.logger.error(result.stderr)
        return None

    def generate_all(self, domain: str = "example.com",
                      project_dir: str = ".",
                      docker_image: str = "easyinstall/wordpress") -> Dict[str, str]:
        """Generate all build system files. Returns {artifact: path} mapping."""
        results = {}
        results["github_actions"] = self.generate_github_actions(
            domain, docker_image, project_dir
        )
        results["dockerfile"] = self.generate_dockerfile(
            output_path=str(Path(project_dir) / "Dockerfile")
        )
        results["makefile"] = self.generate_makefile(
            domain, docker_image,
            output_path=str(Path(project_dir) / "Makefile")
        )
        results["version_bump"] = self.generate_version_bump_script(
            output_path=str(Path(project_dir) / "version_bump.py")
        )
        self.logger.info(f"Build system files generated in {project_dir}")
        return results
