#!/usr/bin/env python3
"""
cloudflare_worker.py — EasyInstall Cloudflare Worker Plugin v1.0
=================================================================
Deploys WordPress edge logic to Cloudflare Workers.
Manages CDN, edge SSL, KV namespaces, rate-limiting and cache rules.

Config : /etc/easyinstall/plugins/cloudflare_worker.json
"""

import json
import os
import subprocess
from pathlib import Path
from typing import Dict, Any

# Plugin manager is imported at runtime from sys.path
try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys
    sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


# ─────────────────────────────────────────────────────────────────────────────
# Worker script templates
# ─────────────────────────────────────────────────────────────────────────────

WORKER_CACHE_TEMPLATE = """\
/**
 * EasyInstall WordPress Edge Cache Worker
 * Generated by easyinstall-plugin cloudflare-worker
 */
const BYPASS_PATHS   = ['/wp-admin/', '/wp-login.php', '/?wc-ajax=', '/cart', '/checkout', '/my-account'];
const STATIC_EXTS    = /\\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|eot)(\\?.*)?$/i;
const CACHE_TTL      = {edge: 86400, browser: 3600};
const RATE_LIMIT_MAX = 300;          // requests per minute per IP

export default {
  async fetch(request, env, ctx) {
    const url      = new URL(request.url);
    const cf       = request.cf || {};
    const clientIP = request.headers.get('CF-Connecting-IP') || 'unknown';

    // ── Rate limiting ────────────────────────────────────────────────────────
    if (env.RATE_LIMIT_KV) {
      const key   = `rl:${clientIP}`;
      const count = parseInt(await env.RATE_LIMIT_KV.get(key) || '0', 10);
      if (count > RATE_LIMIT_MAX) {
        return new Response('Too Many Requests', {
          status: 429,
          headers: {'Retry-After': '60', 'Content-Type': 'text/plain'},
        });
      }
      ctx.waitUntil(
        env.RATE_LIMIT_KV.put(key, String(count + 1), {expirationTtl: 60})
      );
    }

    // ── Bypass dynamic / admin paths ─────────────────────────────────────────
    const shouldBypass =
      request.method !== 'GET' ||
      request.headers.get('Cookie')?.includes('wordpress_logged_in') ||
      request.headers.get('Cookie')?.includes('woocommerce_') ||
      BYPASS_PATHS.some(p => url.pathname.startsWith(p));

    if (shouldBypass) {
      const resp = await fetch(request);
      return addSecurityHeaders(resp);
    }

    // ── Static assets — long cache ───────────────────────────────────────────
    if (STATIC_EXTS.test(url.pathname)) {
      const cache     = caches.default;
      let   cached    = await cache.match(request);
      if (!cached) {
        cached = await fetch(request);
        if (cached.status === 200) {
          const clone = cached.clone();
          ctx.waitUntil(cache.put(request, clone));
        }
      }
      return addSecurityHeaders(cached);
    }

    // ── HTML — edge cache with stale-while-revalidate ────────────────────────
    const cache  = caches.default;
    let   cached = await cache.match(request);
    if (cached) return addSecurityHeaders(cached);

    const origin = await fetch(request);
    if (origin.status === 200) {
      const clone = new Response(origin.clone().body, origin);
      clone.headers.set('Cache-Control', `public, max-age=${CACHE_TTL.edge}`);
      ctx.waitUntil(cache.put(request, clone));
    }
    return addSecurityHeaders(origin);
  },
};

function addSecurityHeaders(response) {
  const r = new Response(response.body, response);
  r.headers.set('X-Frame-Options',           'SAMEORIGIN');
  r.headers.set('X-Content-Type-Options',     'nosniff');
  r.headers.set('Referrer-Policy',            'strict-origin-when-cross-origin');
  r.headers.set('X-XSS-Protection',           '1; mode=block');
  r.headers.set('Permissions-Policy',         'geolocation=(), microphone=()');
  r.headers.set('Strict-Transport-Security',  'max-age=31536000; includeSubDomains');
  return r;
}
"""

WRANGLER_TOML_TEMPLATE = """\
# wrangler.toml — generated by easyinstall-plugin cloudflare-worker
name            = "{worker_name}"
main            = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_DOMAIN = "{domain}"
APP_VERSION = "7.0"

[[kv_namespaces]]
binding     = "RATE_LIMIT_KV"
id          = "{kv_id}"

[env.production]
vars = {{ ENVIRONMENT = "production" }}

[env.preview]
vars = {{ ENVIRONMENT = "preview" }}
"""


# ─────────────────────────────────────────────────────────────────────────────
# Plugin class
# ─────────────────────────────────────────────────────────────────────────────

class CloudflareWorkerPlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name         = "cloudflare-worker",
            version      = "1.0.0",
            description  = "Deploy WordPress edge logic to Cloudflare Workers",
            author       = "EasyInstall",
            requires     = ["node", "npm"],
            provides     = ["edge-cache", "rate-limiting", "edge-ssl"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("node"):
            self.logger.warning("Node.js not found — install it to use wrangler")
        if not self.require_binary("wrangler"):
            self.logger.info("wrangler not installed. Install: npm install -g wrangler")
        return True

    # ── Public methods ────────────────────────────────────────────────────────

    def generate_worker_script(self, output_path: str = "/tmp/worker.js") -> str:
        """Write the cache worker script to disk and return the path."""
        path = Path(output_path)
        path.write_text(WORKER_CACHE_TEMPLATE)
        self.logger.info(f"Worker script written to {path}")
        return str(path)

    def generate_wrangler_config(self, domain: str, worker_name: str = "easyinstall-wp",
                                  kv_id: str = "REPLACE_ME",
                                  output_path: str = "/tmp/wrangler.toml") -> str:
        """Write a wrangler.toml for the given domain and return its path."""
        content = WRANGLER_TOML_TEMPLATE.format(
            worker_name = worker_name,
            domain      = domain,
            kv_id       = kv_id,
        )
        path = Path(output_path)
        path.write_text(content)
        self.logger.info(f"wrangler.toml written to {path}")
        return str(path)

    def deploy_worker(self, domain: str, api_token: str = "", account_id: str = "") -> bool:
        """Deploy the worker via wrangler CLI."""
        if not self.require_binary("wrangler"):
            self.logger.error("wrangler is not installed. Run: npm install -g wrangler")
            return False

        work_dir = Path("/tmp/easyinstall-worker")
        work_dir.mkdir(exist_ok=True)

        self.generate_worker_script(str(work_dir / "worker.js"))
        self.generate_wrangler_config(domain, output_path=str(work_dir / "wrangler.toml"))

        env = os.environ.copy()
        if api_token:
            env["CLOUDFLARE_API_TOKEN"] = api_token
        if account_id:
            env["CLOUDFLARE_ACCOUNT_ID"] = account_id

        result = subprocess.run(
            ["wrangler", "deploy"],
            cwd    = str(work_dir),
            env    = env,
            capture_output = True,
            text   = True,
        )
        if result.returncode == 0:
            self.logger.info(f"Worker deployed successfully for {domain}")
            return True
        self.logger.error(f"Wrangler deploy failed:\n{result.stderr}")
        return False

    def purge_cache(self, zone_id: str, api_token: str) -> bool:
        """Purge Cloudflare cache for the given zone via REST API."""
        import urllib.request
        url  = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/purge_cache"
        data = json.dumps({"purge_everything": True}).encode()
        req  = urllib.request.Request(
            url,
            data    = data,
            headers = {
                "Authorization": f"Bearer {api_token}",
                "Content-Type":  "application/json",
            },
            method = "POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                body = json.loads(resp.read())
                if body.get("success"):
                    self.logger.info("Cloudflare cache purged successfully")
                    return True
                self.logger.error(f"Cache purge failed: {body.get('errors')}")
        except Exception as exc:
            self.logger.error(f"Cache purge exception: {exc}")
        return False

    def set_cache_rules(self, domain: str, rules: Dict[str, Any]) -> Dict:
        """Return a wrangler-compatible routes section dict for the given rules."""
        routes = []
        for pattern, ttl in rules.items():
            routes.append({"pattern": f"{domain}/{pattern}", "ttl": ttl})
        self.logger.info(f"Generated {len(routes)} cache rules for {domain}")
        return {"routes": routes, "domain": domain}
