#!/usr/bin/env python3
"""
debian_package.py — EasyInstall Debian Package Plugin v1.0
===========================================================
Generates .deb packages for EasyInstall sites, manages control files,
post-install/pre-remove hooks, and a simple APT repository skeleton.
"""

import os
import subprocess
import shutil
from pathlib import Path
from typing import Dict, Optional

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys; sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


CONTROL_TEMPLATE = """\
Package: {package_name}
Version: {version}
Architecture: {arch}
Maintainer: {maintainer}
Depends: nginx, php{php_version}-fpm, mariadb-server, redis-server, python3
Section: web
Priority: optional
Description: {description}
 Generated by EasyInstall v7.0
 WordPress high-performance stack for {domain}.
"""

POSTINST_TEMPLATE = """\
#!/bin/bash
set -e
# post-install: enable and start services
for svc in nginx php{php_version}-fpm mariadb redis-server; do
    systemctl enable --now "$svc" 2>/dev/null || true
done
# Run EasyInstall setup
/usr/local/bin/easyinstall install 2>/dev/null || true
echo "[EasyInstall] Post-install complete for {domain}"
"""

PRERM_TEMPLATE = """\
#!/bin/bash
set -e
# pre-remove: backup and graceful teardown
echo "[EasyInstall] Backing up {domain} before removal..."
/usr/local/bin/easyinstall backup {domain} 2>/dev/null || true
echo "[EasyInstall] Pre-remove complete for {domain}"
"""

REPO_DISTRIBUTIONS = """\
Origin:      EasyInstall
Label:       EasyInstall
Suite:       stable
Codename:    stable
Architectures: amd64 arm64
Components:  main
Description: EasyInstall WordPress Stack Repository
"""


class DebianPackagePlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "debian-package",
            version     = "1.0.0",
            description = "Build .deb packages and manage an APT repository for EasyInstall",
            author      = "EasyInstall",
            requires    = ["dpkg-deb", "dpkg-scanpackages"],
            provides    = ["deb-build", "apt-repo"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("dpkg-deb"):
            self.logger.warning("dpkg-deb not found. Install: apt install dpkg-dev")
        return True

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _pkg_name(domain: str) -> str:
        return "easyinstall-" + domain.replace(".", "-")

    def _create_debian_dir(self, build_root: Path) -> Path:
        d = build_root / "DEBIAN"
        d.mkdir(parents=True, exist_ok=True)
        return d

    # ── Public methods ────────────────────────────────────────────────────────

    def build(self, domain: str,
               version: str       = "1.0.0",
               arch: str          = "amd64",
               maintainer: str    = "EasyInstall <noreply@easyinstall.dev>",
               description: str   = "",
               php_version: str   = "8.2",
               output_dir: str    = "/tmp") -> Optional[str]:
        """
        Build a .deb package for the given domain.
        Returns the path to the resulting .deb file, or None on failure.
        """
        pkg_name  = self._pkg_name(domain)
        build_dir = Path(output_dir) / "deb_build" / pkg_name
        if build_dir.exists():
            shutil.rmtree(build_dir)
        build_dir.mkdir(parents=True)

        # DEBIAN control files
        deb_dir = self._create_debian_dir(build_dir)

        (deb_dir / "control").write_text(CONTROL_TEMPLATE.format(
            package_name = pkg_name,
            version      = version,
            arch         = arch,
            maintainer   = maintainer,
            description  = description or f"WordPress stack for {domain}",
            domain       = domain,
            php_version  = php_version,
        ))

        postinst = deb_dir / "postinst"
        postinst.write_text(POSTINST_TEMPLATE.format(
            domain=domain, php_version=php_version
        ))
        postinst.chmod(0o755)

        prerm = deb_dir / "prerm"
        prerm.write_text(PRERM_TEMPLATE.format(domain=domain))
        prerm.chmod(0o755)

        # Include EasyInstall binaries
        bin_dir = build_dir / "usr" / "local" / "bin"
        bin_dir.mkdir(parents=True, exist_ok=True)
        for binary in Path("/usr/local/bin").glob("easyinstall*"):
            shutil.copy2(binary, bin_dir / binary.name)

        # Build
        deb_path = Path(output_dir) / f"{pkg_name}_{version}_{arch}.deb"
        result   = subprocess.run(
            ["dpkg-deb", "--build", "--root-owner-group", str(build_dir), str(deb_path)],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info(f"Package built: {deb_path}")
            return str(deb_path)
        self.logger.error(f"dpkg-deb failed: {result.stderr}")
        return None

    def create_repository(self, repo_dir: str = "/var/www/apt") -> str:
        """
        Initialise a minimal APT repository skeleton.
        After placing .deb files in <repo_dir>/pool/main/, run update_repository().
        """
        pool = Path(repo_dir) / "pool" / "main"
        dists = Path(repo_dir) / "dists" / "stable" / "main" / "binary-amd64"
        pool.mkdir(parents=True, exist_ok=True)
        dists.mkdir(parents=True, exist_ok=True)
        (Path(repo_dir) / "dists" / "stable" / "Release").write_text(REPO_DISTRIBUTIONS)
        self.logger.info(f"APT repo skeleton created at {repo_dir}")
        return repo_dir

    def update_repository(self, repo_dir: str = "/var/www/apt") -> bool:
        """Regenerate Packages.gz for the APT repo."""
        pool = Path(repo_dir) / "pool"
        if not pool.exists():
            self.logger.error(f"Pool directory not found: {pool}")
            return False
        result = subprocess.run(
            f"cd {repo_dir} && dpkg-scanpackages pool/ > dists/stable/main/binary-amd64/Packages"
            f" && gzip -k -f dists/stable/main/binary-amd64/Packages",
            shell=True, capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info("APT repository index updated")
            return True
        self.logger.error(result.stderr)
        return False

    def install_deb(self, deb_path: str) -> bool:
        """Install a .deb package using dpkg."""
        result = subprocess.run(
            ["dpkg", "-i", deb_path], capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info(f"Installed: {deb_path}")
            return True
        self.logger.error(result.stderr)
        return False
