#!/usr/bin/env python3
"""
docker_plugin.py — EasyInstall Docker Plugin v1.0
===================================================
Generates Docker Compose stacks for WordPress sites (WP + MySQL + Redis).
Supports multi-container setups, health checks, volume management,
backup/restore, and optional Docker Swarm mode.
"""

import json
import os
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys
    sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


COMPOSE_TEMPLATE = """\
# docker-compose.yml — generated by easyinstall-plugin docker
# Site: {domain}
version: '3.8'

services:
  wordpress:
    image: wordpress:{wp_version}-php{php_version}-fpm-alpine
    container_name: wp_{safe_domain}
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST:     db:3306
      WORDPRESS_DB_NAME:     {db_name}
      WORDPRESS_DB_USER:     {db_user}
      WORDPRESS_DB_PASSWORD: {db_password}
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wp_data_{safe_domain}:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wp_net_{safe_domain}
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'ok';"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx_{safe_domain}
    restart: unless-stopped
    ports:
      - "{http_port}:80"
      - "{https_port}:443"
    volumes:
      - wp_data_{safe_domain}:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress
    networks:
      - wp_net_{safe_domain}

  db:
    image: mariadb:{mariadb_version}
    container_name: db_{safe_domain}
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: {db_root_password}
      MARIADB_DATABASE:      {db_name}
      MARIADB_USER:          {db_user}
      MARIADB_PASSWORD:      {db_password}
    volumes:
      - db_data_{safe_domain}:/var/lib/mysql
    networks:
      - wp_net_{safe_domain}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p{db_root_password}"]
      interval: 20s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_{safe_domain}
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru --save ""
    volumes:
      - redis_data_{safe_domain}:/data
    networks:
      - wp_net_{safe_domain}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  wp_data_{safe_domain}:
  db_data_{safe_domain}:
  redis_data_{safe_domain}:

networks:
  wp_net_{safe_domain}:
    driver: bridge
"""

PHP_INI_TEMPLATE = """\
; uploads.ini — generated by easyinstall-plugin docker
upload_max_filesize = 64M
post_max_size       = 64M
max_execution_time  = 300
memory_limit        = 256M
"""

NGINX_CONF_TEMPLATE = """\
# nginx.conf — generated by easyinstall-plugin docker
server {{
    listen 80;
    server_name {domain};
    root /var/www/html;
    index index.php;

    client_max_body_size 64M;
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location / {{
        try_files $uri $uri/ /index.php?$args;
    }}

    location ~ \\.php$ {{
        fastcgi_pass   wordpress:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO       $fastcgi_path_info;
        fastcgi_read_timeout 300;
    }}

    location ~* \\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?|ttf)$ {{
        expires    1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    location ~ /\\.ht {{
        deny all;
    }}
}}
"""

SWARM_COMPOSE_TEMPLATE = """\
# docker-stack.yml — Swarm mode, generated by easyinstall-plugin docker
version: '3.8'

services:
  wordpress:
    image: wordpress:{wp_version}-php{php_version}-fpm-alpine
    deploy:
      replicas: {replicas}
      update_config:
        parallelism: 1
        delay:       10s
      restart_policy:
        condition: on-failure
    environment:
      WORDPRESS_DB_HOST:     db:3306
      WORDPRESS_DB_NAME:     {db_name}
      WORDPRESS_DB_USER:     {db_user}
      WORDPRESS_DB_PASSWORD: {db_password}
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_net

  db:
    image: mariadb:{mariadb_version}
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      MARIADB_ROOT_PASSWORD: {db_root_password}
      MARIADB_DATABASE:      {db_name}
      MARIADB_USER:          {db_user}
      MARIADB_PASSWORD:      {db_password}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

volumes:
  wp_data:
    driver: local
  db_data:
    driver: local

networks:
  wp_net:
    driver: overlay
"""


class DockerPlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "docker",
            version     = "1.0.0",
            description = "Docker Compose stacks for WordPress (WP + MySQL + Redis)",
            author      = "EasyInstall",
            requires    = ["docker"],
            provides    = ["container-orchestration"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("docker"):
            self.logger.warning("Docker not found. Install Docker first.")
        return True

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _safe(domain: str) -> str:
        return domain.replace(".", "_").replace("-", "_")

    # ── Public methods ────────────────────────────────────────────────────────

    def generate_compose(self, domain: str,
                         db_name: str         = "",
                         db_user: str         = "",
                         db_password: str     = "secret_wp",
                         db_root_password: str = "secret_root",
                         wp_version: str      = "latest",
                         php_version: str     = "8.2",
                         mariadb_version: str = "10.11",
                         http_port: int       = 80,
                         https_port: int      = 443,
                         output_dir: str      = "/tmp") -> str:
        """
        Generate a full docker-compose.yml for a WordPress site and return
        the path to the compose file.
        """
        safe   = self._safe(domain)
        db_n   = db_name   or f"wp_{safe[:20]}"
        db_u   = db_user   or f"user_{safe[:12]}"
        out    = Path(output_dir) / domain
        out.mkdir(parents=True, exist_ok=True)

        compose_content = COMPOSE_TEMPLATE.format(
            domain           = domain,
            safe_domain      = safe,
            db_name          = db_n,
            db_user          = db_u,
            db_password      = db_password,
            db_root_password = db_root_password,
            wp_version       = wp_version,
            php_version      = php_version,
            mariadb_version  = mariadb_version,
            http_port        = http_port,
            https_port       = https_port,
        )
        (out / "docker-compose.yml").write_text(compose_content)
        (out / "uploads.ini").write_text(PHP_INI_TEMPLATE)
        (out / "nginx.conf").write_text(NGINX_CONF_TEMPLATE.format(domain=domain))

        self.logger.info(f"Compose stack generated in {out}")
        return str(out / "docker-compose.yml")

    def generate_swarm_stack(self, domain: str,
                              replicas: int = 2,
                              db_name: str = "wordpress",
                              db_user: str = "wp_user",
                              db_password: str = "secret_wp",
                              db_root_password: str = "secret_root",
                              wp_version: str = "latest",
                              php_version: str = "8.2",
                              mariadb_version: str = "10.11",
                              output_dir: str = "/tmp") -> str:
        """Generate a Docker Swarm stack file."""
        out = Path(output_dir) / domain
        out.mkdir(parents=True, exist_ok=True)
        content = SWARM_COMPOSE_TEMPLATE.format(
            domain=domain, replicas=replicas, db_name=db_name,
            db_user=db_user, db_password=db_password,
            db_root_password=db_root_password,
            wp_version=wp_version, php_version=php_version,
            mariadb_version=mariadb_version,
        )
        path = out / "docker-stack.yml"
        path.write_text(content)
        self.logger.info(f"Swarm stack written to {path}")
        return str(path)

    def up(self, compose_file: str, detach: bool = True) -> bool:
        """docker compose up for the given compose file."""
        if not self.require_binary("docker"):
            return False
        flags  = ["-d"] if detach else []
        result = subprocess.run(
            ["docker", "compose", "-f", compose_file, "up"] + flags,
            capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info(f"Stack started: {compose_file}")
            return True
        self.logger.error(result.stderr)
        return False

    def down(self, compose_file: str, volumes: bool = False) -> bool:
        """docker compose down."""
        if not self.require_binary("docker"):
            return False
        flags  = ["-v"] if volumes else []
        result = subprocess.run(
            ["docker", "compose", "-f", compose_file, "down"] + flags,
            capture_output=True, text=True
        )
        return result.returncode == 0

    def backup(self, domain: str, output_dir: str = "/var/backups/easyinstall") -> Optional[str]:
        """Dump the database and tar the volumes for a site."""
        safe    = self._safe(domain)
        out     = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        ts      = __import__("datetime").datetime.now().strftime("%Y%m%d_%H%M%S")
        dump_f  = out / f"{domain}_db_{ts}.sql"
        result  = subprocess.run(
            ["docker", "exec", f"db_{safe}",
             "mariadb-dump", "-u", "root",
             "--all-databases", f"--result-file=/tmp/dump.sql"],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            self.logger.error(f"DB dump failed: {result.stderr}")
            return None
        subprocess.run(
            ["docker", "cp", f"db_{safe}:/tmp/dump.sql", str(dump_f)],
            capture_output=True
        )
        self.logger.info(f"Backup written to {dump_f}")
        return str(dump_f)
