#!/usr/bin/env python3
"""
microvm_plugin.py — EasyInstall MicroVM Plugin v1.0
=====================================================
Manages lightweight Firecracker / Cloud Hypervisor microVMs for
WordPress site isolation. Generates VM configs, manages lifecycle,
and handles snapshots.
"""

import json
import subprocess
from pathlib import Path
from typing import Dict, Optional

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys; sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


FIRECRACKER_CONFIG_TEMPLATE = {
    "boot-source": {
        "kernel_image_path": "/opt/microvm/kernels/vmlinux",
        "boot_args":         "console=ttyS0 reboot=k panic=1 pci=off",
    },
    "drives": [
        {
            "drive_id":       "rootfs",
            "path_on_host":   "",  # filled at runtime
            "is_root_device": True,
            "is_read_only":   False,
        }
    ],
    "machine-config": {
        "vcpu_count":   2,
        "mem_size_mib": 512,
    },
    "network-interfaces": [
        {
            "iface_id":            "eth0",
            "host_dev_name":       "",  # tap device name filled at runtime
            "guest_mac":           "AA:FC:00:00:00:01",
            "rx_rate_limiter":     None,
            "tx_rate_limiter":     None,
        }
    ],
}

CLOUD_HYPERVISOR_CONFIG_TEMPLATE = """\
# cloud-hypervisor config — generated by easyinstall-plugin microvm
# Site: {domain}
cpus:
  boot_vcpus: {vcpus}
  max_vcpus:  {vcpus}
memory:
  size: {mem_mib}M
kernel: /opt/microvm/kernels/ch-kernel
cmdline: "root=/dev/vda1 console=hvc0 rw"
disks:
  - path: {rootfs_path}
    readonly: false
net:
  - tap:    {tap_dev}
    mac:    "DE:AD:BE:EF:00:01"
    ip:     {vm_ip}
    mask:   "255.255.255.0"
    gateway: {gateway}
"""

SYSTEMD_VM_UNIT_TEMPLATE = """\
# easyinstall-vm-{safe}.service — systemd unit for microVM {domain}
[Unit]
Description=EasyInstall MicroVM — {domain}
After=network.target

[Service]
Type=simple
ExecStartPre=/usr/local/lib/easyinstall_plugins/_microvm_setup_tap.sh {tap_dev} {vm_ip}
ExecStart=/usr/bin/firecracker --no-api \\
    --config-file /etc/easyinstall/vms/{safe}.json
ExecStop=/usr/bin/killall -9 firecracker
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

TAP_SETUP_SCRIPT = """\
#!/bin/bash
# _microvm_setup_tap.sh — create tap device for microVM
# Usage: _microvm_setup_tap.sh <tap_dev> <vm_ip>
TAP=$1; VM_IP=$2; GATEWAY=$(echo $VM_IP | sed 's/\\.[0-9]*$/.1/')
ip tuntap add dev "$TAP" mode tap 2>/dev/null || true
ip addr add "$GATEWAY/24" dev "$TAP" 2>/dev/null || true
ip link set "$TAP" up
sysctl -w net.ipv4.ip_forward=1 >/dev/null
iptables -t nat -A POSTROUTING -s "${VM_IP%.*}.0/24" -j MASQUERADE 2>/dev/null || true
"""


class MicroVMPlugin(BasePlugin):

    IMAGES_DIR = Path("/opt/microvm/images")
    KERNELS_DIR = Path("/opt/microvm/kernels")
    CONFIGS_DIR = Path("/etc/easyinstall/vms")

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "microvm",
            version     = "1.0.0",
            description = "Firecracker / Cloud Hypervisor microVM isolation for WordPress sites",
            author      = "EasyInstall",
            requires    = ["firecracker"],
            provides    = ["vm-isolation", "microvm-lifecycle", "vm-snapshot"],
        )

    def initialize(self) -> bool:
        self.IMAGES_DIR.mkdir(parents=True, exist_ok=True)
        self.KERNELS_DIR.mkdir(parents=True, exist_ok=True)
        self.CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
        if not self.require_binary("firecracker"):
            self.logger.warning(
                "firecracker not installed. Download from "
                "https://github.com/firecracker-microvm/firecracker/releases"
            )
        return True

    @staticmethod
    def _safe(domain: str) -> str:
        return domain.replace(".", "_").replace("-", "_")

    def _allocate_tap(self, index: int) -> tuple:
        """Return (tap_dev, vm_ip, gateway) for given index."""
        tap = f"vmtap{index}"
        ip  = f"172.16.{index}.2"
        gw  = f"172.16.{index}.1"
        return tap, ip, gw

    def generate_firecracker_config(self, domain: str,
                                     vcpus: int = 2,
                                     mem_mib: int = 512,
                                     rootfs_path: str = "",
                                     vm_index: int = 0,
                                     output_dir: Optional[str] = None) -> str:
        """Write a Firecracker JSON config and return its path."""
        safe = self._safe(domain)
        tap, vm_ip, _ = self._allocate_tap(vm_index)
        out  = Path(output_dir) if output_dir else self.CONFIGS_DIR

        cfg = dict(FIRECRACKER_CONFIG_TEMPLATE)
        cfg = json.loads(json.dumps(cfg))  # deep copy
        cfg["drives"][0]["path_on_host"]              = rootfs_path or str(self.IMAGES_DIR / f"{safe}.ext4")
        cfg["network-interfaces"][0]["host_dev_name"] = tap
        cfg["machine-config"]["vcpu_count"]           = vcpus
        cfg["machine-config"]["mem_size_mib"]         = mem_mib

        path = out / f"{safe}.json"
        path.write_text(json.dumps(cfg, indent=2))
        self.logger.info(f"Firecracker config written to {path}")
        return str(path)

    def generate_cloud_hypervisor_config(self, domain: str,
                                          vcpus: int = 2,
                                          mem_mib: int = 512,
                                          vm_index: int = 0,
                                          output_dir: Optional[str] = None) -> str:
        """Write a Cloud Hypervisor YAML config and return its path."""
        safe = self._safe(domain)
        tap, vm_ip, gateway = self._allocate_tap(vm_index)
        out  = Path(output_dir) if output_dir else self.CONFIGS_DIR

        content = CLOUD_HYPERVISOR_CONFIG_TEMPLATE.format(
            domain     = domain,
            vcpus      = vcpus,
            mem_mib    = mem_mib,
            rootfs_path= str(self.IMAGES_DIR / f"{safe}.img"),
            tap_dev    = tap,
            vm_ip      = vm_ip,
            gateway    = gateway,
        )
        path = out / f"{safe}-ch.yml"
        path.write_text(content)
        self.logger.info(f"Cloud Hypervisor config written to {path}")
        return str(path)

    def generate_systemd_unit(self, domain: str, vm_index: int = 0,
                               output_dir: str = "/etc/systemd/system") -> str:
        """Generate a systemd unit that starts the Firecracker VM."""
        safe = self._safe(domain)
        tap, vm_ip, _ = self._allocate_tap(vm_index)

        # Write tap setup helper
        helper = Path("/usr/local/lib/easyinstall_plugins/_microvm_setup_tap.sh")
        helper.write_text(TAP_SETUP_SCRIPT)
        helper.chmod(0o755)

        unit = SYSTEMD_VM_UNIT_TEMPLATE.format(
            safe=safe, domain=domain, tap_dev=tap, vm_ip=vm_ip
        )
        path = Path(output_dir) / f"easyinstall-vm-{safe}.service"
        path.write_text(unit)
        self.logger.info(f"Systemd VM unit written to {path}")
        return str(path)

    def create_rootfs(self, domain: str, size_mb: int = 2048) -> str:
        """Create a blank ext4 rootfs image for the VM."""
        safe  = self._safe(domain)
        image = self.IMAGES_DIR / f"{safe}.ext4"
        if image.exists():
            self.logger.info(f"Rootfs already exists: {image}")
            return str(image)
        result = subprocess.run(
            ["dd", "if=/dev/zero", f"of={image}", "bs=1M", f"count={size_mb}"],
            capture_output=True
        )
        subprocess.run(["mkfs.ext4", str(image)], capture_output=True)
        self.logger.info(f"Rootfs created: {image} ({size_mb}MB)")
        return str(image)

    def snapshot(self, domain: str, snapshot_dir: str = "/opt/microvm/snapshots") -> Optional[str]:
        """Take a memory + disk snapshot of a running Firecracker VM via the API socket."""
        safe   = self._safe(domain)
        socket = f"/tmp/firecracker-{safe}.sock"
        snap   = Path(snapshot_dir) / safe
        snap.mkdir(parents=True, exist_ok=True)
        payload = json.dumps({
            "snapshot_type":      "Full",
            "snapshot_path":      str(snap / "snapshot"),
            "mem_file_path":      str(snap / "mem"),
        }).encode()
        import urllib.request
        req = urllib.request.Request(
            f"http+unix://{socket}/snapshot/create",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="PUT",
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as r:
                self.logger.info(f"Snapshot created: {snap}")
                return str(snap)
        except Exception as exc:
            self.logger.error(f"Snapshot failed: {exc}")
            return None
