#!/usr/bin/env python3
"""
podman_plugin.py — EasyInstall Podman Plugin v1.0
===================================================
Rootless container support via Podman.
Generates podman-compose files, systemd unit files (Quadlet / legacy),
and auto-update configuration for WordPress sites.
"""

import subprocess
from pathlib import Path
from typing import Optional

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys; sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


PODMAN_COMPOSE_TEMPLATE = """\
# podman-compose.yml — generated by easyinstall-plugin podman
# Site: {domain}  (rootless)
version: '3'

services:
  wordpress:
    image: docker.io/library/wordpress:{wp_version}-php{php_version}-fpm-alpine
    container_name: wp_{safe}
    restart: unless-stopped
    userns_mode: keep-id
    environment:
      WORDPRESS_DB_HOST:     127.0.0.1:3306
      WORDPRESS_DB_NAME:     {db_name}
      WORDPRESS_DB_USER:     {db_user}
      WORDPRESS_DB_PASSWORD: {db_pass}
    volumes:
      - $HOME/sites/{domain}/html:/var/www/html:Z
    network_mode: slirp4netns

  db:
    image: docker.io/library/mariadb:{mariadb_version}
    container_name: db_{safe}
    restart: unless-stopped
    userns_mode: keep-id
    environment:
      MARIADB_ROOT_PASSWORD: {db_root_pass}
      MARIADB_DATABASE:      {db_name}
      MARIADB_USER:          {db_user}
      MARIADB_PASSWORD:      {db_pass}
    volumes:
      - $HOME/sites/{domain}/db:/var/lib/mysql:Z
    network_mode: slirp4netns

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redis_{safe}
    restart: unless-stopped
    userns_mode: keep-id
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    volumes:
      - $HOME/sites/{domain}/redis:/data:Z
    network_mode: slirp4netns
"""

QUADLET_TEMPLATE = """\
# {safe}.container — Quadlet unit (Podman 4.4+)
# Place in ~/.config/containers/systemd/
[Unit]
Description=WordPress ({domain}) via Podman
After=network-online.target

[Container]
Image=docker.io/library/wordpress:{wp_version}-php{php_version}-fpm-alpine
ContainerName=wp_{safe}
Environment=WORDPRESS_DB_HOST=127.0.0.1:3306
Environment=WORDPRESS_DB_NAME={db_name}
Environment=WORDPRESS_DB_USER={db_user}
Environment=WORDPRESS_DB_PASSWORD={db_pass}
Volume=%h/sites/{domain}/html:/var/www/html:Z
Network=slirp4netns

[Service]
Restart=always
TimeoutStartSec=120

[Install]
WantedBy=default.target
"""

LEGACY_SYSTEMD_TEMPLATE = """\
# easyinstall-wp-{safe}.service — legacy systemd unit (no Quadlet)
[Unit]
Description=WordPress site {domain} via Podman
After=network.target

[Service]
Type=forking
Restart=on-failure
RestartSec=10
ExecStartPre=-/usr/bin/podman rm -f wp_{safe}
ExecStart=/usr/bin/podman run -d \\
    --name wp_{safe} \\
    --userns keep-id \\
    -e WORDPRESS_DB_HOST=127.0.0.1:3306 \\
    -e WORDPRESS_DB_NAME={db_name} \\
    -e WORDPRESS_DB_USER={db_user} \\
    -e WORDPRESS_DB_PASSWORD={db_pass} \\
    -v %h/sites/{domain}/html:/var/www/html:Z \\
    docker.io/library/wordpress:{wp_version}-php{php_version}-fpm-alpine
ExecStop=/usr/bin/podman stop wp_{safe}

[Install]
WantedBy=multi-user.target
"""

AUTO_UPDATE_TIMER = """\
# podman-auto-update.timer override
[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=3600
"""


class PodmanPlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "podman",
            version     = "1.0.0",
            description = "Rootless WordPress containers via Podman with systemd integration",
            author      = "EasyInstall",
            requires    = ["podman"],
            provides    = ["rootless-containers", "quadlet", "auto-update"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("podman"):
            self.logger.warning("Podman not installed. Install: apt install podman")
        return True

    @staticmethod
    def _safe(domain: str) -> str:
        return domain.replace(".", "_").replace("-", "_")

    def generate_compose(self, domain: str,
                         db_name: str = "wordpress", db_user: str = "wp_user",
                         db_pass: str = "secret", db_root_pass: str = "root_secret",
                         wp_version: str = "latest", php_version: str = "8.2",
                         mariadb_version: str = "10.11",
                         output_dir: str = "/tmp") -> str:
        """Generate a podman-compose.yml."""
        safe = self._safe(domain)
        out  = Path(output_dir) / domain
        out.mkdir(parents=True, exist_ok=True)
        content = PODMAN_COMPOSE_TEMPLATE.format(
            domain=domain, safe=safe, db_name=db_name, db_user=db_user,
            db_pass=db_pass, db_root_pass=db_root_pass,
            wp_version=wp_version, php_version=php_version,
            mariadb_version=mariadb_version,
        )
        path = out / "podman-compose.yml"
        path.write_text(content)
        self.logger.info(f"podman-compose.yml written to {path}")
        return str(path)

    def generate_quadlet(self, domain: str,
                          db_name: str = "wordpress", db_user: str = "wp_user",
                          db_pass: str = "secret",
                          wp_version: str = "latest", php_version: str = "8.2",
                          output_dir: str = "/tmp") -> str:
        """Generate a Quadlet .container file (Podman ≥ 4.4)."""
        safe = self._safe(domain)
        out  = Path(output_dir) / domain
        out.mkdir(parents=True, exist_ok=True)
        content = QUADLET_TEMPLATE.format(
            domain=domain, safe=safe, db_name=db_name,
            db_user=db_user, db_pass=db_pass,
            wp_version=wp_version, php_version=php_version,
        )
        path = out / f"{safe}.container"
        path.write_text(content)
        self.logger.info(f"Quadlet unit written to {path}")
        return str(path)

    def generate_systemd_unit(self, domain: str,
                               db_name: str = "wordpress", db_user: str = "wp_user",
                               db_pass: str = "secret",
                               wp_version: str = "latest", php_version: str = "8.2",
                               output_dir: str = "/tmp") -> str:
        """Generate a legacy systemd unit (fallback for older Podman)."""
        safe = self._safe(domain)
        out  = Path(output_dir) / domain
        out.mkdir(parents=True, exist_ok=True)
        content = LEGACY_SYSTEMD_TEMPLATE.format(
            domain=domain, safe=safe, db_name=db_name,
            db_user=db_user, db_pass=db_pass,
            wp_version=wp_version, php_version=php_version,
        )
        path = out / f"easyinstall-wp-{safe}.service"
        path.write_text(content)
        self.logger.info(f"Legacy systemd unit written to {path}")
        return str(path)

    def enable_auto_update(self, user_systemd_dir: str = "~/.config/systemd/user") -> bool:
        """Enable podman-auto-update timer for rootless containers."""
        d = Path(user_systemd_dir).expanduser()
        d.mkdir(parents=True, exist_ok=True)
        timer_override = d / "podman-auto-update.timer.d"
        timer_override.mkdir(exist_ok=True)
        (timer_override / "override.conf").write_text(AUTO_UPDATE_TIMER)
        result = subprocess.run(
            ["systemctl", "--user", "enable", "--now", "podman-auto-update.timer"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info("Podman auto-update timer enabled")
            return True
        self.logger.warning(f"Could not enable timer: {result.stderr.strip()}")
        return False

    def run(self, compose_file: str) -> bool:
        """Start containers via podman-compose."""
        if not self.require_binary("podman-compose"):
            self.logger.error("podman-compose not found. Install: pip install podman-compose")
            return False
        result = subprocess.run(
            ["podman-compose", "-f", compose_file, "up", "-d"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info("Podman stack started")
            return True
        self.logger.error(result.stderr)
        return False
