#!/usr/bin/env python3
"""
ts_worker.py — EasyInstall TypeScript Worker Plugin v1.0
=========================================================
Generates TypeScript Cloudflare Worker projects with:
  - Full TypeScript source templates
  - Wrangler deploy configuration
  - Type definitions (Cloudflare Workers types)
  - Deno import maps
  - Vitest-based test scaffolding
"""

import subprocess
import json
from pathlib import Path
from typing import Dict, Optional

try:
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata
except ImportError:
    import sys; sys.path.insert(0, "/usr/local/lib")
    from easyinstall_plugin_manager import BasePlugin, PluginMetadata


# ─────────────────────────────────────────────────────────────────────────────
# TypeScript templates
# ─────────────────────────────────────────────────────────────────────────────

TS_INDEX_TEMPLATE = """\
/**
 * EasyInstall WordPress Edge Worker — TypeScript
 * Domain: {domain}
 * Generated by easyinstall-plugin ts-worker
 */

export interface Env {{
  RATE_LIMIT_KV?: KVNamespace;
  WS_SECRET?:     string;
  ENVIRONMENT?:   string;
}}

const BYPASS_PATHS: string[] = [
  '/wp-admin/', '/wp-login.php', '/wp-json/', '/?wc-ajax=',
];

const STATIC_PATTERN = /\\.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?)(\\?.*)?$/i;

async function handleRequest(
  request: Request,
  env:     Env,
  ctx:     ExecutionContext,
): Promise<Response> {{
  const url      = new URL(request.url);
  const shouldBypass =
    request.method !== 'GET' ||
    BYPASS_PATHS.some(p => url.pathname.startsWith(p)) ||
    (request.headers.get('Cookie') ?? '').includes('wordpress_logged_in');

  if (shouldBypass) {{
    return addSecurityHeaders(await fetch(request));
  }}

  const cache    = caches.default;
  const cacheKey = new Request(url.toString());

  const cached = await cache.match(cacheKey);
  if (cached) return cached;

  const response = await fetch(request);
  if (response.status === 200) {{
    const ttl = STATIC_PATTERN.test(url.pathname) ? 86400 : 300;
    const clone = new Response(response.clone().body, response);
    clone.headers.set('Cache-Control', `public, max-age=${{ttl}}`);
    ctx.waitUntil(cache.put(cacheKey, clone));
  }}
  return addSecurityHeaders(response);
}}

function addSecurityHeaders(response: Response): Response {{
  const r = new Response(response.body, response);
  r.headers.set('X-Frame-Options',          'SAMEORIGIN');
  r.headers.set('X-Content-Type-Options',    'nosniff');
  r.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  r.headers.set('Referrer-Policy',           'strict-origin-when-cross-origin');
  r.headers.delete('X-Powered-By');
  return r;
}}

export default {{
  fetch: handleRequest,
}} satisfies ExportedHandler<Env>;
"""

TS_TEST_TEMPLATE = """\
/**
 * Vitest tests for EasyInstall WordPress Edge Worker
 * Run: npx vitest run
 */
import {{ describe, it, expect, vi, beforeEach }} from 'vitest';
import worker from './index';

const makeRequest = (url: string, opts: RequestInit = {{}}) =>
  new Request(url, {{ method: 'GET', ...opts }});

const mockEnv   = {{}};
const mockCtx   = {{ waitUntil: vi.fn(), passThroughOnException: vi.fn() }};

// Mock global fetch
global.fetch = vi.fn().mockResolvedValue(
  new Response('<html>WordPress</html>', {{
    status:  200,
    headers: {{ 'Content-Type': 'text/html' }},
  }})
);

describe('EasyInstall Worker', () => {{
  beforeEach(() => vi.clearAllMocks());

  it('returns a response for normal requests', async () => {{
    const resp = await worker.fetch(makeRequest('https://example.com/'), mockEnv, mockCtx);
    expect(resp.status).toBe(200);
  }});

  it('adds security headers', async () => {{
    const resp = await worker.fetch(makeRequest('https://example.com/'), mockEnv, mockCtx);
    expect(resp.headers.get('X-Frame-Options')).toBe('SAMEORIGIN');
    expect(resp.headers.get('X-Content-Type-Options')).toBe('nosniff');
  }});

  it('bypasses cache for wp-admin paths', async () => {{
    const resp = await worker.fetch(
      makeRequest('https://example.com/wp-admin/'), mockEnv, mockCtx
    );
    expect(resp.status).toBe(200);
    // waitUntil should NOT be called (no cache put)
    expect(mockCtx.waitUntil).not.toHaveBeenCalled();
  }});

  it('bypasses cache for logged-in users', async () => {{
    const resp = await worker.fetch(
      makeRequest('https://example.com/', {{
        headers: {{ Cookie: 'wordpress_logged_in_abc=1' }},
      }}),
      mockEnv, mockCtx
    );
    expect(resp.status).toBe(200);
  }});
}});
"""

TSCONFIG_TEMPLATE = """\
{
  "compilerOptions": {
    "target":          "ES2022",
    "module":          "ES2022",
    "moduleResolution": "bundler",
    "lib":             ["ES2022"],
    "types":           ["@cloudflare/workers-types"],
    "strict":          true,
    "noUnusedLocals":  true,
    "noImplicitReturns": true,
    "esModuleInterop": true,
    "skipLibCheck":    true,
    "outDir":          "dist"
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
"""

PACKAGE_JSON_TEMPLATE = """\
{{
  "name": "{safe}-worker",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "build":   "tsc",
    "deploy":  "wrangler deploy",
    "dev":     "wrangler dev",
    "test":    "vitest run",
    "preview": "wrangler deploy --env preview"
  }},
  "dependencies": {{
    "@cloudflare/workers-types": "^4.0.0"
  }},
  "devDependencies": {{
    "typescript":   "^5.4.0",
    "vitest":       "^1.5.0",
    "wrangler":     "^3.0.0"
  }}
}}
"""

WRANGLER_TOML_TS_TEMPLATE = """\
# wrangler.toml — TypeScript Worker for {domain}
name            = "{safe}-worker"
main            = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SITE_DOMAIN = "{domain}"
ENVIRONMENT = "development"

[env.production]
name = "{safe}-worker"
vars = {{ SITE_DOMAIN = "{domain}", ENVIRONMENT = "production" }}

[env.preview]
name = "{safe}-worker-preview"
vars = {{ SITE_DOMAIN = "{domain}", ENVIRONMENT = "preview" }}
"""

DENO_IMPORT_MAP_TEMPLATE = """\
{{
  "imports": {{
    "@cloudflare/workers-types/": "npm:@cloudflare/workers-types/",
    "vitest":                     "npm:vitest@^1.5.0"
  }}
}}
"""


class TypeScriptWorkerPlugin(BasePlugin):

    def get_metadata(self) -> PluginMetadata:
        return PluginMetadata(
            name        = "ts-worker",
            version     = "1.0.0",
            description = "TypeScript Cloudflare Worker project scaffolding with Wrangler, Vitest, and type defs",
            author      = "EasyInstall",
            requires    = ["node", "npm"],
            provides    = ["ts-worker", "worker-types", "vitest-tests"],
        )

    def initialize(self) -> bool:
        if not self.require_binary("node"):
            self.logger.warning("Node.js not found — needed for TypeScript compilation")
        if not self.require_binary("npm"):
            self.logger.warning("npm not found")
        return True

    @staticmethod
    def _safe(domain: str) -> str:
        return domain.replace(".", "-").replace("_", "-")

    def scaffold(self, domain: str, output_dir: str = "/tmp") -> str:
        """
        Scaffold a complete TypeScript Worker project for the given domain.
        Returns the project root directory path.
        """
        safe    = self._safe(domain)
        project = Path(output_dir) / f"{safe}-worker"
        src     = project / "src"
        src.mkdir(parents=True, exist_ok=True)

        # Source
        (src / "index.ts").write_text(TS_INDEX_TEMPLATE.format(domain=domain))
        (src / "index.test.ts").write_text(TS_TEST_TEMPLATE)

        # Config files
        (project / "tsconfig.json").write_text(TSCONFIG_TEMPLATE)
        (project / "package.json").write_text(
            PACKAGE_JSON_TEMPLATE.format(safe=safe)
        )
        (project / "wrangler.toml").write_text(
            WRANGLER_TOML_TS_TEMPLATE.format(domain=domain, safe=safe)
        )
        (project / "deno.json").write_text(
            DENO_IMPORT_MAP_TEMPLATE
        )
        (project / ".gitignore").write_text(
            "node_modules/\ndist/\n.wrangler/\n*.env\n"
        )

        self.logger.info(f"TypeScript worker project scaffolded: {project}")
        return str(project)

    def install_deps(self, project_dir: str) -> bool:
        """Run npm install in the project directory."""
        if not self.require_binary("npm"):
            return False
        result = subprocess.run(
            ["npm", "install", "--silent"],
            cwd=project_dir, capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info(f"npm deps installed in {project_dir}")
            return True
        self.logger.error(result.stderr)
        return False

    def build(self, project_dir: str) -> bool:
        """Compile TypeScript via tsc."""
        if not self.require_binary("tsc"):
            # Try via npx
            result = subprocess.run(
                ["npx", "tsc", "--noEmit"],
                cwd=project_dir, capture_output=True, text=True
            )
        else:
            result = subprocess.run(
                ["tsc", "--noEmit"],
                cwd=project_dir, capture_output=True, text=True
            )
        if result.returncode == 0:
            self.logger.info("TypeScript compilation successful")
            return True
        self.logger.error(f"TypeScript errors:\n{result.stdout}\n{result.stderr}")
        return False

    def run_tests(self, project_dir: str) -> bool:
        """Run Vitest tests."""
        result = subprocess.run(
            ["npx", "vitest", "run"],
            cwd=project_dir, capture_output=True, text=True
        )
        if result.returncode == 0:
            self.logger.info("All tests passed")
            return True
        self.logger.error(f"Tests failed:\n{result.stdout}")
        return False

    def deploy(self, project_dir: str, env: str = "production") -> bool:
        """Deploy the TypeScript worker via wrangler."""
        if not self.require_binary("wrangler"):
            result = subprocess.run(
                ["npx", "wrangler", "deploy", "--env", env],
                cwd=project_dir, capture_output=True, text=True
            )
        else:
            result = subprocess.run(
                ["wrangler", "deploy", "--env", env],
                cwd=project_dir, capture_output=True, text=True
            )
        if result.returncode == 0:
            self.logger.info(f"Worker deployed ({env})")
            return True
        self.logger.error(result.stderr)
        return False

    def generate_type_defs(self, output_path: str = "/tmp/worker-types.d.ts") -> str:
        """Write a minimal standalone type definition file for offline use."""
        dts = """\
// EasyInstall Worker — minimal type definitions (offline)
// For full types: npm install @cloudflare/workers-types

interface KVNamespace {
  get(key: string): Promise<string | null>;
  put(key: string, value: string, options?: { expirationTtl?: number }): Promise<void>;
  delete(key: string): Promise<void>;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface ExportedHandler<Env = {}> {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Response | Promise<Response>;
}

declare function caches(): { default: Cache };
"""
        Path(output_path).write_text(dts)
        self.logger.info(f"Type definitions written: {output_path}")
        return output_path
