name = "easyinstallvps"
main = "src/index.js"  # यह सही पाथ होना चाहिए
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Global variables
[vars]
APP_NAME = "EasyInstallVPS"
APP_VERSION = "1.0.0"
GITHUB_REPO_OWNER = "sugan0927"
GITHUB_REPO_NAME = "easyinstallvps"

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }
